### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by HegedusB** [pedronachtigall/CodAn#2]
I recently tried to run the CodAn program but immediately after the start it stopped with this error message: 
"""
2019-10-24 14:10:45 >>>> starting CodAn (v1.0 September 2019)...
        transcript file -> collapsed_transcripts.fasta
        model -> CodAn_models/FUNGI_full/
        strand prediction -> plus
        number of threads -> 10
2019-10-24 14:10:45 >>>> CDS prediction...
2019-10-24 14:10:45 >>>> retrieving sequences...
        number of transcripts -> 17163
        number of predictions -> 0
Traceback (most recent call last):
  File "/SSD/software/CodAn/bin/codan.py", line 478, in <module>
    __main__()
  File "/SSD/software/CodAn/bin/codan.py", line 458, in __main__
    _codan_PLUS_(options.transcripts, options.output_folder, options.model, options.cpu)
  File "/SSD/software/CodAn/bin/codan.py", line 323, in _codan_PLUS_
    _retrieveORF_PLUS_(transcripts, outF)
  File "/SSD/software/CodAn/bin/codan.py", line 90, in _retrieveORF_PLUS_
    os.remove(transcripts+".index")
FileNotFoundError: [Errno 2] No such file or directory: 'collapsed_transcripts.fasta.index'
"""
Do you have any idea about what went wrong? Thank for any help!

**Comment by pedronachtigall** [comment]
Hi @HegedusB 

Thank you for considering to use CodAn in your analysis.

As I noticed, CodAn is not performing the prediction, cause your are facing problems with perl modules (bioperl or MCE library), so try to install bioperl and MCE (by apt ```apt-get install bioperl libmce-perl``` or CPAN). It should work.

Then, before using your own sequences, try to run our [quick tutorial](https://github.com/pedronachtigall/CodAn/tree/master/tutorial) using our [test sequences](https://github.com/pedronachtigall/CodAn/blob/master/tutorial/transcripts.fa).

If CodAn worked properly with the test sequences, but it is failing with your sequences, you are probably having trouble with your sequences. Ensure that the headers don't have symbols such as ":" or "|" or " "(space).

Moreover, the Bio::DB::Fasta library is responsible for creating the .index. It can't process a fasta file with lines containing more than 65,536 characters. So, if you have any large sequence in one unique line, do the following:

- download the script [BreakLines.py](https://github.com/pedronachtigall/CodAn/blob/master/scripts/BreakLines.py)
- run BreakLines script using the following command:
    -```python3 BreakLines.py input.fasta output_breaklines.fasta```
- use the "output_breaklines.fasta" to run CodAn.

Let me know if I helped you or if you are still having problems to run CodAn.

Best regards,
Pedro

**Comment by ayoshiaki** [comment]
Make sure that you can run this command before executing codan.py:

Try to execute the following commands (without any parameter) to test your setup. If something is wrong, then the error will appear. 

``` 
[darwin: ~/CodAn/codan/bin]$ ls -l
total 3292
-rwxr-xr-x 1 1000 1000   19761 Oct  1 17:11 codan.py
-rwxr-xr-x 1 1000 1000     613 Sep  1 20:32 fasta_to_tops
-rwxr-xr-x 1 1000 1000   13870 Sep  6 17:03 predict
-rwxr-xr-x 1 1000 1000 3328096 Sep  1 20:32 tops-viterbi_decoding
```

```
[darwin: ~/CodAn/codan/bin]$ cd
[darwin: ~]$ export PATH=$PATH:$HOME/CodAn/codan/bin
```

```
[darwin: ~]$ tops-viterbi_decoding
tops-viterbi_decoding: ToPS version "master 00f9ed6"

Allowed options:
  -h [ --help ]         produce help message
  -m [ --model ] arg    a decodable model
  -F [ --fasta ]        use fasta format
```

```
[darwin: ~]$ predict
ERROR: missing fasta file name !
USAGE: predict [-g <genome> | -t <transcriptome> | -z <local transcriptome predictor> | -s <local genome predictor] -f <fasta file> [-c <number of cpu>]
```

```
[darwin: ~]$ codan.py

       _____           _  ___
      /  __ \         | |/ _ \
      | /  \/ ___   __| / /_\ \_ __
      | |    / _ \ / _` |  _  | '_ \
      | \__/\ (_) | (_| | | | | | | |
       \____/\___/ \__,_\_| |_/_| |_|


>>>> CodAn v1.0 September 2019 <<<<
****Use -h for help!****

BASIC USAGE (find CDS and UTR sequences):
codan.py -t transcripts.fa -o output_folder -m model_folder

ALTERNATIVE USAGE (predict CDS and UTR sequences and perform BLAST search  in specific DB to annotated predicted genes based on similarity):
codan.py -t transcripts.fa -o output_folder -m model_folder -b blast_DB

```

**Comment by HegedusB** [comment]
Thanks all of your suggestions. Based on them, I have reinstalled the bioperl, libmce-perl programs. As a result the CodAn now ran on the test dataset without any errors message but predicts zero CDSs. I am a little confused. 

"""
2019-10-25 08:58:44 >>>> starting CodAn (v1.0 September 2019)...
        transcript file -> transcripts.fa
        model -> ../CodAn_models/VERT_full
        strand prediction -> both
        number of threads -> 1
2019-10-25 08:58:44 >>>> CDS prediction...
2019-10-25 09:00:47 >>>> retrieving sequences...
        number of transcripts -> 500
        number of predictions -> 0
                predictions at plus strand -> 0
                predictions at minus strand -> 0
2019-10-25 09:00:47 >>>> prediction finished!
        CDS -> CodAn_output/ORF_sequences.fasta
        3'UTR -> CodAn_output/3utr_sequences.fasta
        5'UTR -> CodAn_output/5utr_sequences.fasta
        GTF file -> CodAn_output/annotation.gtf
"""

**Comment by ayoshiaki** [comment]
What is your operating system? How much RAM your setup has got? 

This happens when the program **tops-viterbi_decoding** is not operating well. 

Can you execute the following command without any error?

``` head -10  transcripts.fa | tops-viterbi_decoding -m  ../CodAn_models/VERT_full  ```

**Comment by HegedusB** [comment]
I ran the CodAn on a server which has a CentOS 7.6.1810 operation system and 192 Gb RAMs. 
After I executed the command I have got this massage: 
"""
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
"""

**Comment by pedronachtigall** [comment]
Hi @HegedusB ,

Running the tutorial on my computer resulted in predictions on the test dataset:
number of transcripts -> 500
number of predictions -> 487
predictions at plus strand -> 486
predictions at minus strand -> 1

You are still probably having problems with

**Comment by ayoshiaki** [comment]
> I ran the CodAn on a server which has a CentOS 7.6.1810 operation system and 192 Gb RAMs.
> After I executed the command I have got this massage:
> """
> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> Aborted
> """

Thank you! I will try to use CentOS to see a solution to your problem.

**Comment by HegedusB** [comment]
Thank you! Is there any operation system you would recommend.

**Comment by ayoshiaki** [comment]
We tested with Ubuntu (eoan). You can try to compile [ToPS](https://github.com/ayoshiaki/tops) in your system.  I will test it and then sent you more instructions.

**Comment by ayoshiaki** [comment]
Hi @HegedusB, 

I made a mistake, the correct command to test the tops-viterbi_decoding is:

'''
[darwin ~]$ cd ~/CodAn/models/VERT_full/ghmm && head -15 ~/CodAn/tutorial/transcripts.fa | tops-viterbi_decoding -m model/ghmm_intronless.model  -F

TIME: 0.055124
NM_212842: -1853.89:	begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin start start start start start start start CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CD ....
'''

**Comment by HegedusB** [comment]
Hi @ayoshiaki,

The new command is working! 
"""
[bhegedus@node2 ghmm]$ head -15 ../../../CodAn_test/transcripts.fa | tops-viterbi_decoding -m model/ghmm_intronless.model  -F
TIME: 0
NM_212842: -1853.89:    begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin begin start start start start start start start CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS CDS """

**Comment by ayoshiaki** [comment]
You have everything right.
I am really trying to understand why are you having zero predictions.  *tops-viterbi_decoding* is predicting the CDS, and everything is running correctly. @pedronachtigall, do you have any idea?

**Comment by pedronachtigall** [comment]
Hi @HegedusB 

I run a test using the test dataset on my computer and it returned the following output:
	number of transcripts -> 500
	number of predictions -> 487
		predictions at plus strand -> 486
		predictions at minus strand -> 1

So, no issues with the test dataset.

Considering that all dependencies are working well at your OS, it is really strange is printing ZERO predictions in the test dataset. Looking at the time of processing of each step, the test dataset is being processed, but the problem can be on reading/writing files at the "retrieving sequences: step. Did you take a look at the output files to check if they are empty or have the prediction results on them?

Do you have any Desktop with linux or MacOS available to try to run CodAn using its computer instead of using the server? If not, can you re-install your python environment or [create a new environment with conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) to install the biopython dependencies, activate the environment and then run CodAn?

**Comment by pedronachtigall** [comment]
Hi @HegedusB 

Sorry, but I have another idea to check if the problem is related with the python dependencies.
Try to run the predict script from the CodAn/bin folder using the test dataset as follow:

```predict -z path/to/VERT_full -f transcripts.fa > predict_out```

then use ```head``` to check the first ten lines of the "predict_out" file:

```head predict_out```

Check if the ```head``` print the same output as follow:
```

NM_001006016	CodAn	start_codon	81	83	 -2179.69	+	0gene_id "CodAn.1"; transcript_id "CodAn.1";
NM_001006016	CodAn	CDS	81	1619	 -2179.69	+	0	gene_id "CodAn.1"; transcript_id "CodAn.1";
NM_001006016	CodAn	stop_codon	1620	1622	 -2179.69	+	0gene_id "CodAn.1"; transcript_id "CodAn.1";

NM_001007055	CodAn	start_codon	37	39	 -1789.71	+	0gene_id "CodAn.2"; transcript_id "CodAn.2";
NM_001007055	CodAn	CDS	37	585	 -1789.71	+	0	gene_id "CodAn.2"; transcript_id "CodAn.2";
NM_001007055	CodAn	stop_codon	586	588	 -1789.71	+	0gene_id "CodAn.2"; transcript_id "CodAn.2";

NM_001008780	CodAn	start_codon	105	107	 -3745.55	+	0gene_id "CodAn.3"; transcript_id "CodAn.3";
```

**Comment by HegedusB** [comment]
Dear Pedro,

Thank you for the test instructions. Indeed it was "predict" that failed due to "permission error" on file "/tmp/err". As it turned out, the file remained in the tmp folder after a run-test carried out by a colleague of mine. Since the file was not writable for my user account, analysis failed. I wonder, can you please ensure that separate tmp file would be generated for each run so that the pipeline would be safe to be run by multiple users on the same node.
Thank you for your help,

**Comment by ayoshiaki** [comment]
Thank you @HegedusB ! 

@pedronachtigall, I submitted a pull request to fix the problem with */tmp/err* file.

**Comment by pedronachtigall** [comment]
Hi @ayoshiaki ... I already add your request to the predict file.

Hi @HegedusB , we updated the "predict" file to redirect to "/tmp/null" instead of "/tmp/err".
So, download our updated tarball and try to run CodAn, it should work on your system now!

Let me know if it is working or if you have any other issues.
