### ISSUE TITLE
Empty files after the prediction

### ISSUE THREAD

**Issue by AstrMary** [pedronachtigall/CodAn#8]
Hi,

First of all thank you for your tool!! 

I try to run the below command 
./codan.py -t   /data-nfs/maria/trinity_out_dir/Trinity.fasta -o test_olea -m  /data-nfs/maria/CodAn/models/PLANTS_partial

but I got the below info

2021-02-11 09:20:13 >>>> starting CodAn (v1.0 September 2019)...
	transcript file -> /data-nfs/maria/trinity_out_dir/Trinity.fasta
	model -> /data-nfs/maria/CodAn/models/PLANTS_partial
	strand prediction -> both
	number of threads -> 1
2021-02-11 09:20:13 >>>> CDS prediction...
2021-02-11 09:20:19 >>>> retrieving sequences...
	number of transcripts -> 245510
	number of predictions -> 0
		predictions at plus strand -> 0
		predictions at minus strand -> 0
rm: cannot remove 'test_olea/minus.fa.*': No such file or directory
rm: cannot remove '/data-nfs/maria/trinity_out_dir/Trinity.fasta.index*': No such file or directory
2021-02-11 09:20:23 >>>> prediction finished!
	CDS -> test_olea/ORF_sequences.fasta
	3'UTR -> test_olea/3utr_sequences.fasta
	5'UTR -> test_olea/5utr_sequences.fasta
	GTF file -> test_olea/annotation.gtf
 and the generated files were empty..
What am I doing wrong?
Thank you for your help,
Mary

**Comment by pedronachtigall** [comment]
Hi Mary (@AstrMary),

Thank you for using CodAn in your analysis.

I did not face this issue before on any server/computer I installed and run CodAn.
Few questions to try to help you:

Are you using CodAn on a server or on your own computer?
Did you follow the conda environment installation procedure or tried to install any requirements separately?
 - Please, follow the conda env installation procedure (it helps to ensure that everything is working properly): ```conda create -n codan_env python=3.6 biopython=1.69 perl perl-bioperl perl-mce blast``` -> then activate ```conda activate conda_env```
 - Installing the requirements separately may be tricky and not work well, depending on the computer/server you are trying to set up the installation.

Is the model decompressed (i.e., did you run the command ```gzip -d PLANTS_partial.zip```)?

There are some sequences too large in your input?
 - If yes, can you run the following script ```CodAn/scripts/BreakLines.py input.fasta output_breaklines.fasta``` and use the "output_breaklines.fasta" as input to run CodAn.
 - the predict module uses the Bio::DB::Fasta library to create the .index. Maybe the error is related to this package. It can't process a fasta file with lines containing more than 65,536 characters.

Best,
Pedro

**Comment by AstrMary** [comment]
Dear Pedro,

Thank you for your reply.. 
 
After the conda install -c bioconda perl-bioperl-core installation the problem solved then I followed your instuctions and voilà  I have annotation file for my sample :-).

Thank you very much,
Maria

**Comment by pedronachtigall** [comment]
Hi @AstrMary ,

I am glad to know that CodAn is properly working now.
Just let me know if you have any other issues or questions.

Best,
Pedro
